### ISSUE TITLE
Add --skip-publish option, like --skip-git

### ISSUE THREAD

**Issue by eirslett** [lerna/lerna#127]
The idea would be that you could run `lerna publish --skip-publish` (a somewhat strange command if you read it like that) and it would do the git update, git tag, git push etc., but not `npm publish` the packages.

The motivation is that you could then setup Travis CI to do the releasing*. Travis already supports [vanilla npm publish](https://docs.travis-ci.com/user/deployment/npm/), but one could easily write a lerna publisher, that ran `lerna publish --skip-git` instead of `npm publish`.

So `.travis.yml` would look like this:

```yml
# build config etc. first

# deploy config
deploy:
  provider: lerna
  email: email@example.com
  api_key:
    secure: XXX
  on:
    tags: true
    repo: some/repo
```

It would also require an update to [https://github.com/travis-ci/dpl](Dpl), which is Travis' deployment tool, so that it could support lerna.

Otherwise, I have to tell you, Lerna is great! I use it for publishing [zipkin-js](https://github.com/openzipkin/zipkin-js) and the user experience is very smooth.

(*I hate releasing stuff from my Windows computer, because it does weird things to file permissions, and also I tend to mess up my local repo, so it's not a clean build like on Travis. And of course, I forget to run the tests too)
