### ISSUE TITLE
Publish command needs more docs around Travis-CI configuration

### ISSUE THREAD

**Issue by jedmao** [lerna/lerna#2022]
It took me way too long and far too many Travis-CI builds to figure out the right configuration for Travis-CI to run `lerna publish` with everything it needed. I'm still not 100% sure if everything I'm doing is necessary, but perhaps it will help others to share my findings. Even better if there was some documentation around this.

## My goals

1. Automatically `npm publish` each relevant package in the monorepo when a PR is merged into master.
1. Automatically cut a release by pushing a publish commit via `git push`.
1. Only do the above on Travis-CI builds on the master branch.

## Solution

Add `.npmrc` to `.gitignore`.

### .travis.yml

```yml
after_success:
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
  - git remote add pub https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
  - git fetch pub master # needed?
  - git checkout master # got an error w/o this one

deploy:
  - provider: script
    script: npx lerna publish --git-remote pub
    skip_cleanup: true
    keep_history: true
    on:
      branch: master
```

Shouldn't the `GH_TOKEN` and `TRAVIS_REPO_SLUG` automatically be used in the first place? I'm hoping there's an easier way to compress these steps.

### lerna.json

```jsonc
{
  "packages": ["packages/*"],
  "version": "independent",
  "command": {
    "publish": {
      "conventionalCommits": true,
      "yes": true // Needed in the CI env? I don't want to wait for another build to find out.
    }
  }
}
```

## Conclusion

Be great if there was some documentation around all these steps together.
