### ISSUE TITLE
--github-release sometimes fails with "Validation Failed"

### ISSUE THREAD

**Issue by christophehurpeau** [lerna/lerna#2038]
I use `--github-release` on several repos and sometimes it fails.

Example of fail here :
https://circleci.com/gh/ornikar/shared-configs/875

Example of success here :
https://circleci.com/gh/ornikar/shared-configs/884

This is not a token autorisation issue.
I initially thought it was related to having private packages in the repo, but this one doesn't have any.

How can we help debug this issue ?

**Comment by fc** [comment]
I was curious myself.. here is a stack trace by following the trail of the code executed:
https://github.com/lerna/lerna/blob/master/commands/version/index.js#L645-L653
https://github.com/lerna/lerna/blob/master/utils/github-client/lib/github-client.js#L33
https://github.com/octokit/rest.js/blob/d6918d9564ec8977bd7df77fac3be06f4559049c/plugins/rest-api-endpoints/routes.json#L7122-L7154

The root cause of the error is in `@octokit/rest`... and that's as far as I got.

**Comment by evocateur** [comment]
I believe this is due to a sorting bug, fixed it [here](https://github.com/lerna/lerna/compare/master...evocateur:fix-github-release-tag-search) but I need time to write a test.

**Comment by milesj** [comment]
@evocateur Pretty sure it's that. I have these packages and it fails:

```
Changes:
 - lunar-apollo: 1.0.1 => 1.0.2
 - lunar-app-shell: 1.0.1 => 1.0.2
 - lunar: 1.1.0 => 1.1.1
 - lunar-forms: 1.0.1 => 1.0.2
 - lunar-icons: 1.0.1 => 1.0.2
 - lunar-layouts: 1.0.1 => 1.0.2
 - lunar-metrics: 1.0.1 => 1.0.2
 - lunar-test-utils: 1.0.1 => 1.0.2 (private)
```

Obviously the "lunar" is going to cause issues.
