### ISSUE TITLE
Lerna version in github action impossible without setting GH_TOKEN in push

### ISSUE THREAD

**Issue by morgs32** [lerna/lerna#2118]
## Expected Behavior
I'd like to be able to run lerna version (with changelog too) and push to master. I could create another admin user for the bot but still there's no way to use that in the `gitPushToRemote` that happens in `/commands/version/lib/push.js`.

## Current Behavior
I'm using a github action. And it uses a generic GITHUB_TOKEN with permissions that I cannot set. 

## Possible Solution
Perhaps we could make `gitPushToRemote` use the same GH_TOKEN as the `createRelease` method?

## Steps to Reproduce (for bugs)
I'll create a repo if you think necessary. Just let me know?

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "3.0.0-beta.14",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "version": "independent",
  "command": {
    "publish": {
      "message": "chore(release): publish [ci skip]",
      "allowBranch": "master"
    }
  }
}
```
</p></details>

## Your Environment
"lerna": "^3.13.4",

| OS | Version |
| --- | --- |
| github-action | N/A |

**Comment by morgs32** [comment]
I have also spent a lot of time thinking about how else to get CI/CD to generate changelog and commit it to master.
I thought maybe I could get a branch called `release` and on every merge to master it rebases and runs `lerna version --conventional-changelog` and sits there ready to `merge and rebase`. This would generate git tags though, and on every rebase, given the new commit SHAs, those tags are abandoned AND we remake them. Not sure if that would even work without first removing them in the first place (from the old branch).

I tend to think that doing `lerna version ...` on CI/CD and merging to `master` is still the best possible solution.

Thoughts?

**Comment by revelt** [comment]
hi Morgan, tickets about existing CI setups are very hard to troubleshoot because a proper way is to isolate the CI actions, step by step, add copious amounts of CI logging and work logically what needs to be achieved. Like when making Bash scripts, it's best to assemble them step by step, little by little. Also, "Support" people here are unpaid and often on different platforms (I'm on GitLab CI for example) so excuse for my quite vague suggestions and thoughts below.

---

> but still there's no way to use that in the gitPushToRemote that happens in `/commands/version/lib/push.js`

Personally, I switched to "normal" `git push`, at the very end of CI operation chain. See the CI yml script at the bottom.

> I tend to think that doing lerna version --conventional-changelog --github-release on CI/CD and merging to master is still the best possible solution.

That's what I do, see CI pipeline yml below.

> maybe I could get a branch...

I'd avoid branches to keep things simpler.

---

Just a thought. Conceptually, if we talk about GitLab/GitHub where some sort of CI is provided on the same service as Git repo, it can be challenging to transfer the build artifacts from CI (newly-built changelogs etc.) into git repository **"internally"**, from CI to "git origin". On GitLab it's [not possible](https://stackoverflow.com/questions/40122780/push-files-to-gitlab-ci-via-ci-runner) to "git commit" and "git push" **internally** between the CI and repo. It has to be done from CI as if it was from an outsider — with full git/npm logins, as if you hired a person who did this from their computer. CI can pull off this **"external"** way if you tackle all the "sharp edges" (like login secrets not leaking, detached git head and complex scripting chains where CI calls npm scripts and/or make scripts).

It seems this "internal" push is possible on GitHub Actions - https://stackoverflow.com/questions/55657835/is-there-a-way-to-push-changes-with-a-github-action — but maybe not? Either way, it seems GitHub Actions is not a fully-fledged CI. Maybe I'm wrong.

---

If it helps, here's my GitLab CI recipe which publishes all npm packages, commits everything and pushes to the origin. Notice how I `echo` everything even remotely useful at every step. For example, `git status` helped me to detect issue when git head was detached and later to see what files were changed. Another example, yesterday this CI script failed because I `git add`ed only `packages` folder but there were updates made to root `readme.md` too and git didn't push and pipeline failed at step 5. I haven't updated `readme.md` for a while in CI scripts so all went well until CI updated `readme`. That `git add readme.md` is new since yesterday. Generally, echo everything and make sure CI build output (not script files but CI website pages which show what's happening) is concealed from public in case secrets leak. GitLab allows to conceal CI pages from public. Haven't checked GitHub's.

```yml

#
#    C O D S E N
#

deploy:
  except:
    - tags
  image: node:latest
  stage: deploy
  script:
    - git config --global credential.helper store
    - git remote set-url origin https://gitlab-ci-token:$PERSONAL_ACCESS_TOKEN@gitlab.com/codsen/codsen.git
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - git config --global user.name "$YOUR_NAME_SURNAME"
    - npm set unsafe-perm true -g
    - npm set //registry.npmjs.org/:_authToken $NPM_TOKEN -g
    - npm set username $NPM_USERNAME -g
    - npm set email $NPM_EMAIL -g
    - echo "git user:"
    - git config user.name
    - echo "npm user:"
    - npm whoami
    - echo '█████████████████████████████ 1 █████████████████████████████'
    - git status
    - git checkout master
    - echo '█████████████████████████████ 2 █████████████████████████████'
    - git status
    - npm run bootstrap
    - echo '█████████████████████████████ 3 █████████████████████████████'
    - git status
    - npm run all:test:only
    - echo '█████████████████████████████ 4 █████████████████████████████'
    - git status
    - npm run readme:generate
    - echo '█████████████████████████████ 5 █████████████████████████████'
    - git status
    - git add packages
    - git add readme.md
    - "git commit -m '[skip ci] chore: Automated build tasks' --no-verify"
    - npx lerna changed
    - npm run pub:vers
    - echo '█████████████████████████████ 6 █████████████████████████████'
    - git status
    - git add packages
    - echo '█████████████████████████████ 7 █████████████████████████████'
    - git status
    - "git commit -m '[skip ci] chore: Automated build tasks' --no-verify"
    - echo '█████████████████████████████ 8 █████████████████████████████'
    - git status
    - npm run republish
    - echo '█████████████████████████████ 9 █████████████████████████████'
    - git status
    - git push origin master
    - echo '█████████████████████████████ 10 █████████████████████████████ - done'
```

Anybody else with GH Actions experience please advise. Let's help each other 👍
