### ISSUE TITLE
Problem with the circleci runtime `Cannot find module 'xxx'`

### ISSUE THREAD

**Issue by chenyueban** [lerna/lerna#2182]
## Expected Behavior
I have packages scoped `@foo/a`,`@foo/b`,`@foo/c`
`@foo/a` depends on `@foo/b` and `@foo/c` two packages
I get an error when I run unit tests with circleci.
but I have no problem running locally.

## Current Behavior
```
FAIL @foo/a src/Navigation/__tests__/Navigation.test.tsx
  ● Test suite failed to run

    TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
    src/Navigation/__tests__/Navigation.test.tsx:4:61 - error TS2307: Cannot find module '@foo/b'.

    4 import { GlobalNavigationButton, Connected, Settings } from '@foo/b'

STACK: 
Failed to collect coverage from /tmp/xxx/packages/foo-a/src/Command/Command.tsx
ERROR: TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
src/Command/Command.tsx:2:34 - error TS2307: Cannot find module '@foo/b'.

2 import { More as MoreIcon } from '@foo/b'
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "npmClient": "yarn",
  "version": "independent",
  "useWorkspaces": true,
  "command": {
    "publish": {
      "npmClient": "npm",
      "verifyAccess": false,
      "ignoreChanges": ["*.md", "**/test/**"],
      "message": "chore(release): publish %s"
    }
  }
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.14.1 |
| `npm --version`  | 6.4.1 |
| `yarn --version` | 1.10.1 |
| `node --version` | 10.15.3 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS Mojave | 10.14.5 |

Here is my circleci configuration
```
version: 2.1

defaults: &defaults
  working_directory: /tmp/xxx
  docker:
    - image: circleci/node:10.15.3

commands:
  install_js:
    steps:
      - restore_cache:
          keys:
            - v2-yarn-sha-{{ checksum "yarn.lock" }}
            - v2-yarn-sha-
      - run:
          name: Install js dependencies
          command: yarn
      - run:
          name: Bootstrap
          command: yarn bootstrap

jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - install_js
      - run:
          name: Should not have any git not staged
          command: git diff --exit-code
      - save_cache:
          key: v2-yarn-sha-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn/v4
  test_unit:
    <<: *defaults
    steps:
      - checkout
      - install_js
      - run:
          name: Test_unit
          command: yarn test:prod

workflows:
  version: 2
  pipeline:
    jobs:
      - checkout:
          filters:
            branches:
              ignore: l10n
      - test_unit:
          requires:
            - checkout
```

If you still need any information, please leave a message.
