### ISSUE TITLE
How do I release an initial version of a package with conventional commits?

### ISSUE THREAD

**Issue by fseglard** [lerna/lerna#2509]
Hi,

Let's say I have a monorepo configured with Lerna in independent mode with 3 packages:

* Package A (1.0.0)
* Package B (1.1.0)
* Package C (2.0.0)

The package A is new and has never been released. The packages B and C have already been released.

My package A contains some features (`feat: xxx`) as it's his first release.
The other 2 packages contain only fixes (`fix: xxx`).

I want to do a release so I use `lerna publish --conventional-commits`. But here, Lerna is displaying me this:

```
Changes:
 - packagea: 1.0.0 => 1.1.0
 - packageb: 1.1.0 => 1.1.1
 - packagec: 2.0.0 => 2.0.1
```

Should the release version of package A not be 1.0.0, as it has never been released before?

Is there any documentation/examples about on how to release a new package with conventional commits?

Thanks in advance for any of your feedbacks!
