### ISSUE TITLE
Lerna doesn't work on CI

### ISSUE THREAD

**Issue by IgorBabkin** [lerna/lerna#2705]
I use Gitlab as CI and have job for master branch. When I run this job the get en DETACHED HEAD error. But the job runs on the latest (NOT detached head)

```
image: node:latest

variables:
  GIT_STRATEGY: clone

stages:
  - staging

cache:
  paths:
    - packages/*/.vercel/
    - node_modules/

before_script:
  - npm i -g vercel lerna
  - lerna bootstrap --hoist

deploy-staging:
  stage: staging
  tags:
    - lemonstand
  script:
    - lerna publish --yes
  only:
    - master
```

## Current Behavior
```
$ lerna publish --yes
info cli using local version of lerna
lerna notice cli v3.22.1
lerna info versioning independent
lerna info ci enabled
lerna ERR! ENOGIT Detached git HEAD, please checkout a branch to choose versions.
ERROR: Job failed: exit code 1
```

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.22.1 |

![image](https://user-images.githubusercontent.com/1428790/92003368-3d942e80-ed41-11ea-92cd-fddf3e732f5a.png)

**Comment by CurrrBell** [comment]
Having the same issue in my GitLab CI. I've tried myriad combinations of `--force-publish`, `--no-git-tag-version`, and similar flags to no avail.

**Comment by vonkanehoffen** [comment]
I have it working with:
```
lerna:
  image: node:12.18.3
  stage: deploy
  script:
    - git config --global user.name "lerna-bot"
    - git config --global user.email "lerna-bot@aurora.io"
    - git remote set-url origin "https://gitlab-ci-token:$GIT_ACCESS_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git"
    - git checkout -B "$CI_COMMIT_REF_NAME" "$CI_COMMIT_SHA"
    - npm config set @your-scope-here:registry=https://gitlab.com/api/v4/packages/npm/
    - npm config set '//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken' "${CI_JOB_TOKEN}"
    - npm config set '//gitlab.com/api/v4/packages/npm/:_authToken' "${CI_JOB_TOKEN}"
    - yarn
    - npm run lerna-publish --registry=https://gitlab.com/api/v4/packages/npm/
```

Think it could be neater, but the above works. Hope that helps :-D
