### ISSUE TITLE
conventional commits/changelog adds all previous commits to release (not .gitconfig)

### ISSUE THREAD

**Issue by iDVB** [lerna/lerna#2720]
Literally identical to #1532
However, this **only** happens on [GitHub Actions](https://github.com/features/actions), and works perfectly locally.
... and there does not seem to be any `.gitconfig` `[format]` settings in the action when running this command...

```
git config --list --show-origin

file:/etc/gitconfig	filter.lfs.smudge=git-lfs smudge -- %f
file:/etc/gitconfig	filter.lfs.process=git-lfs filter-process
file:/etc/gitconfig	filter.lfs.required=true
file:/etc/gitconfig	filter.lfs.clean=git-lfs clean -- %f
file:.git/config	core.repositoryformatversion=0
file:.git/config	core.filemode=true
file:.git/config	core.bare=false
file:.git/config	core.logallrefupdates=true
file:.git/config	remote.origin.url=https://github.com/NOTTELLING/NOTTELLING
file:.git/config	remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
file:.git/config	gc.auto=0
file:.git/config	http.https://github.com/.extraheader=AUTHORIZATION: basic ***
file:.git/config	branch.master.remote=origin
file:.git/config	branch.master.merge=refs/heads/master
```

I compared to my local gitconfig and only thing that looks different are a few aliases but no core configs for format.

The only other thing that I can think this could be is related to [another Lerna + GitHub Actions issue](https://github.com/lerna/lerna/issues/2542) that has us cloning the repo via...
```
    steps:
      - uses: actions/checkout@v2
        with:
          # pulls all commits (needed for lerna / semantic release to correctly version)
          fetch-depth: "0"
      # pulls all tags (needed for lerna / semantic release to correctly version)
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
```

Perhaps there is something lost in this type of clone that is breaking things?

**[UPDATE]**
Managed to get this working after finding [a similar project](https://github.com/narative/gatsby-theme-novela/blob/master/.github/workflows/publish.yml#L25-L31) that works by adding a few extra steps. 
Although, not entirely sure what was the fix.

```
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        # pulls all commits (needed for lerna / semantic release to correctly version) — see https://github.com/lerna/lerna/issues/2542
        fetch-depth: "0"
    - name: Git Identity
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Prepare repository
      run: git checkout "${GITHUB_REF:11}"
    - name: Fetch
      # see https://github.com/lerna/lerna/issues/2542
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Pulling
      run: git pull
```
