### ISSUE TITLE
Lerna publish with github action fails when having a packages with an executable referance

### ISSUE THREAD

**Issue by bentrynning** [lerna/lerna#2753]
Lerna is behaving strange when adding executable referance in package.json like below 
```
"bin": {
    "lerna-bin": "./bin/start.js"
  }
```
## Expected Behavior
Lerna to publish package as normal.

## Current Behavior
```
> lerna publish from-package --yes

lerna notice cli v3.22.1
lerna info versioning independent
lerna info ci enabled
lerna ERR! EUNCOMMIT Working tree has uncommitted changes, please commit or remove the following changes before continuing:
lerna ERR! EUNCOMMIT  M packages/lerna-bin/bin/start.js
```

## Steps to Reproduce (for bugs)
1. Create a simple package in a lerna project
2. Add a bin folder (could be named anything)
3. Point to the executable file with the `bin` key as showed in the example abow
4. Try to publish the package with Github actions

Github action example
```
name: lerna release
on:
  push:
    branches:
      - 'tweak/**'
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://npm.pkg.github.com"
          scope: <YOUR_SCOPE>
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ***
      - name: Build Packages for Release
        run: yarn build
      - name: Publish Release
        run: npm run publish
        env:
          NODE_AUTH_TOKEN: ***
```

## Context
It doesn't matter which folder or what name you give the executable node file. As long as you have ha bin key (in package.json) pointing to a file in your repository. Add changes and commit, lerna will fail when trying to publish the package with github actions. When you running `lerna publish from-package --yes` localy everything works fine. And it seams like lerna is doing something in ci context but can't figure out why and how.

| `lerna --version` | 3.22.1 |
| `npm --version`  | 16.x |
| `node --version` | 12.x |

***Could be that this is more related to Github actions (workflows) and should be postet somewhere else***

**Comment by jamiehaywood** [comment]
@bentrynning did you have a solution for this?

**Comment by sholohov** [comment]
Same problem, what should I do? Has anyone solved the problem?

**Comment by cainsyake** [comment]
I have same problem, i try to change the bin path, but still not working.

**Comment by sholohov** [comment]
Will there be any solution?

**Comment by sholohov** [comment]
> In this case, however, I strongly recommend using npx (it's built in to npm so is already available anywhere npm is) to resolve the locally installed lerna version for running commands, rather than trying manually craft a bin path.

That's what I do :)

> Folks this issue is over 2.5 years old, it's best if you have an issue to report it directly instead of commenting on an old closed one. Please report things with as much detail as possible, naturally the best thing to do is provide a minimal reproduction of the issue.

OK

**Comment by SchollSimon** [comment]
Still an issue

**Comment by sholohov** [comment]
I found a deep solution for myself, maybe it will help someone :)

````yaml
cache:
  untracked: true
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - "**/node_modules/"

.common:
  before_script:
    - git checkout -B $CI_COMMIT_BRANCH
    - git reset --hard # fixes bug with modify files in the bin directory
````
