### ISSUE TITLE
lerna -yarn.lock cache issue for single package 

### ISSUE THREAD

**Issue by novaknole** [lerna/lerna#2882]
I am using Lerna. This is more like a question than the issue..

I have the project structure like this:

```
packages/
        package1/
        package2/
        package3/
```

now I am doing the CI/CD on github workflow. The idea is that I do it only for package2, which means that when the push happens, I want to run workflow for `package2/`. The idea is simple:  it's a react project.  I need to do `yarn install` and `yarn build`. 

Now, i am trying to cache node_modules so that if `yarn.lock` doesn't change, I don't have to run `yarn install`. 

The problem is that `package2/` doesn't contain `yarn.lock` because of lerna. So I can't use `actions/cache2` action in my workflow.

I was thinking something like this:

```
- name: Cache yarn modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: yarn-${{ hashFiles('yarn.lock') }}
```

but as I said, `yarn.lock` won't be there. 

I don't want to use root `yarn.lock` because if some other package in my `package1/` or `package3/` got updated, then yarn install would run again..
