### ISSUE TITLE
Lerna 401 - Unable to Publish as part of CI

### ISSUE THREAD

**Issue by andrewcharnley** [lerna/lerna#2907]
v4.0.0

I've set up a repo and confirmed I can publish to github private store using a private token. The next step is to get Lerna working in GitHub actions. So far I've spent half a day trying to get it past a 401.

I've tried writing the correct token to home, root and a few other methods but nothing is working out. I've created a separate CI_USER_TOKEN which has full access.

I have replaced the real org with @myOrg

```

env:
  IN_DOCKER: 1
  DOCKER_REGISTRY: ghcr.io
  NPM_TOKEN: ${{ secrets.CI_USER_TOKEN }}

jobs:

  publish:
    if: "!contains(github.event.head_commit.author.name, 'Lerna AutoBump')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_USER_TOKEN }}
      - uses: actions/setup-node@v1
        with:
          token: ${{ secrets.CI_USER_TOKEN }}
          node-version: '14.x'
      - name: Setup
        run: |
          git config user.name "Lerna AutoBump"
      - name: Install & build
        run: npm run init
      - name: Publish npm packages
        run: |
          git checkout -- package-lock.json
          echo "@myOrg:registry=https://npm.pkg.github.com" >> ~.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.CI_USER_TOKEN }}" >> ~.npmrc
          npx lerna publish --yes --no-verify-access
      - name: Log into docker registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login $DOCKER_REGISTRY -u ${{ github.actor }} --password-stdin
      - name: Push docker images
        run: |
          docker-compose -f docker-compose.ci.yml build
          docker-compose -f docker-compose.ci.yml push
```

Output

lerna info git Pushing tags...
lerna info publish Publishing packages to npm...
lerna notice Skipping all user and access validation due to third-party registry
lerna notice Make sure you're authenticated properly ¯\_(ツ)_/¯
lerna http fetch PUT 401 https://npm.pkg.github.com/@myOrg%2fpackagename 376ms
lerna ERR! E401 Unable to authenticate, need: Basic realm="GitHub Package Registry"
Error: Process completed with exit code 1.
