### ISSUE TITLE
Lerna publish fails randomly in CICD flow

### ISSUE THREAD

**Issue by fannychan** [lerna/lerna#3047]
Lerna publish fails in Github action occasionally. Most times when we deploy, everything works well and packages are published in an expected way. However, several times it has happened that with the same configuration with lerna and unchanged job commands the publish step fails.

## Expected Behavior
Running in our CI should not give the same reoccuring error.

```
run: npx lerna publish --yes --no-verify-access --ignore-scripts --registry ${{ env.NPM_REGISTRY }}
```

## Current Behavior
The publish error happens randomly in  Github Action. It happens maybe every two day or once a week. So far I havn't seen any pattern when this error occurs. The publish step works as expected all the other times.

```
lerna ERR! Error: Command failed with exit code 1: git remote update
lerna ERR! fatal: could not read Username for 'https://github.com': No such device or address
lerna ERR! error: Could not fetch origin
```

Our GH action job with lerna publish
```
jobs:
  install:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          token: ${{ env.GITHUB_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Output yarn cache-dir
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Save the yarn cache directory
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Install project dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Check yarn.lock file
        run: yarn check --integrity

      - name: Run bootstrap
        run: yarn bootstrap

      - name: Run preparetranslations script
        run: yarn preparetranslations

      - uses: actions/cache@v2
        id: cache-install
        with:
          path: ./*
          key: '${{ github.sha }}-install'

  build-core:
    runs-on: ubuntu-20.04
    needs: install
    steps:
      - uses: actions/cache@v2
        id: restore-install
        with:
          path: ./*
          key: '${{ github.sha }}-install'
      - name: Build core
        run: yarn build:core
      - uses: actions/cache@v2
        id: cache-build-core
        with:
          path: ./*
          key: '${{ github.sha }}-build-core'

  version:
    runs-on: ubuntu-20.04
    needs: build-core
    steps:
      - uses: actions/cache@v2
        id: restore-build-core
        with:
          path: ./*
          key: '${{ github.sha }}-build-core'
      - name: Set git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - uses: actions/setup-node@v2
        with:
          registry-url: ${{ env.NPM_REGISTRY }}
      - name: Version and release packages
        run: npx lerna publish --yes --no-verify-access --ignore-scripts --registry ${{ env.NPM_REGISTRY }}
```
        
lerna.json

```
{
  "packages": [
    "packages/*",
    "packages/core/*"
  ],
  "version": "independent",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "command": {
    "publish": {
      "conventionalCommits": true,
      "verifyAccess": false,
      "message": "chore: release"
    }
  }
}
```

## Your Environment
| Executable      | Version |
| ----------- | ----------- |
|`lerna --version` | 4.0.0 |
 `yarn --version` | 1.22.17 
 `node --version` | 14 

 Ubuntu  20.04.3 

I hope I explained the issue descriptively enough!
Any help on where I should start looking would be so much appreciated!
