### ISSUE TITLE
[Question] Where does Lerna get the information that populates "Looking for changed packages since" ?

### ISSUE THREAD

**Issue by dep** [lerna/lerna#3095]
This isn't a bug report, more of a question.

When I run `npx lerna publish --conventional-commits --registry https://npm.pkg.github.com` I see the following output:

```
lerna notice cli v4.0.0
lerna info versioning independent
lerna info ci enabled
lerna success run No packages found with the lifecycle script 'tsc'
lerna notice cli v4.0.0
lerna info versioning independent
lerna info ci enabled
info Looking for changed packages since @foo/redacted-aggregated-storybook@0.0.62
info ignoring diff in paths matching [
info ignoring diff in paths matching   '**/CHANGELOG.md',
info ignoring diff in paths matching   '**/node_modules/**',
info ignoring diff in paths matching   '**/package.json',
info ignoring diff in paths matching   '**/*.md'
info ignoring diff in paths matching ]
info getChangelogConfig Successfully resolved preset "conventional-changelog-angular"
```

In particular I'm very curious where Lerna receives the information to populate this line:

```
info Looking for changed packages since @foo/redacted-aggregated-storybook@0.0.62
```

In looking at my codebase, `0.0.62` is a very out of date package reference (this package is at `2.x` now).  I can't find any references in my codebase to `0.0.62`, so I am quite confused where that version comes from.

Here's my `lerna.json`

```
{
  "packages": ["applications/**", "components/**", "config/**"],
  "version": "independent",
  "command": {
    "bootstrap": {
      "hoist": true,
      "strict": true
    },
    "publish": {
      "conventionalCommits": true,
      "exact": true,
      "message": "chore(release): publish",
      "yes": true
    }
  },
  "ignoreChanges": [
    "**/CHANGELOG.md",
    "**/node_modules/**",
    "**/package.json",
    "**/*.md"
  ]
}
```

And my github action:

```
name: '[Publish]: Mainline Webpack & Manifest'

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - main
    paths:
      - 'components/**'
      - 'config/**'
      - 'applications/react/**'
      - 'applications/poc/**'
      - '!applications/aggregated-storybook/**'

jobs:
  workflow_run:
    if: "!contains(github.event.head_commit.author.name, 'it-redacted')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REDACTED_PACKAGE_MANAGER_TOKEN }}
          fetch-depth: "0"
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
          registry-url: 'https://npm.pkg.github.com'
      - name: Configure git
        run: |
          git config --global user.name it-redacted
          git config --global user.email it@redacted.com
          git fetch --all
      - name: Build
        run: |
          make all
      - name: Version & Publish
        run: |
          npx lerna run tsc && npx lerna publish --conventional-commits --registry https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.REDACTED_PACKAGE_MANAGER_TOKEN }}
```

Thanks in advance!
