### ISSUE TITLE
Lerna bootstrap fails due to concurrency (with npm)

### ISSUE THREAD

**Issue by Reinmar** [lerna/lerna#789]
The latest RC version fails when running `lerna bootstrap`. I'm not sure when it was introduced, though, because only today builds started failing on Travis while RC3 was released 8 days ago. So, I may be actually running into two separate issues. Both turned to have the same solution, though, switching off concurrency.

The issue, at least now, can be reproduced in the following way:

```
p@m /workspace/test> git clone git@github.com:ckeditor/ckeditor5.git
Cloning into 'ckeditor5'...
remote: Counting objects: 6484, done.
remote: Compressing objects: 100% (71/71), done.
remote: Total 6484 (delta 32), reused 0 (delta 0), pack-reused 6407
Receiving objects: 100% (6484/6484), 1.16 MiB | 336.00 KiB/s, done.
Resolving deltas: 100% (3672/3672), done.
p@m /workspace/test> cd ckeditor5/
(master cbe80fd) p@m /workspace/test/ckeditor5> lerna bootstrap
Lerna v2.0.0-rc.3
Bootstrapping 1 packages
Preinstalling packages
Installing external dependencies
Installing hoisted dependencies into root
Pruning hoisted dependencies
FileSystemUtilities.rename    ("./package.json", "./package.json.lerna_backup")
Error: ENOENT: no such file or directory, rename '/workspace/test/ckeditor5/package.json' -> '/workspace/test/ckeditor5/package.json.lerna_backup'
    at Error (native)
NpmUtilities.installInDir     (".", ["guppy-pre-commit@^0.4.0"], {})
Error: ENOENT: no such file or directory, rename '/workspace/test/ckeditor5/package.json' -> '/workspace/test/ckeditor5/package.json.lerna_backup'
    at Error (native)
Errored while running BootstrapCommand.execute
Error: ENOENT: no such file or directory, rename '/workspace/test/ckeditor5/package.json' -> '/workspace/test/ckeditor5/package.json.lerna_backup'
    at Error (native)
```

When I try with `--concurrency=1` the issue doesn't seem to appear:

```
(master cbe80fd) p@m /workspace/test/ckeditor5> lerna bootstrap --concurrency=1
Lerna v2.0.0-rc.3
Bootstrapping 1 packages
Preinstalling packages
Installing external dependencies
Installing hoisted dependencies into root
Pruning hoisted dependencies
Symlinking packages and binaries
Postinstalling packages
Prepublishing packages
Successfully bootstrapped 1 packages.
```

It also proved to help with a bit more complicated situation I had on Travis: https://travis-ci.org/ckeditor/ckeditor5/builds/226105896. It worked well after disabling concurrency: https://travis-ci.org/ckeditor/ckeditor5/builds/226101027.

I can see that similar issues were already reported: https://github.com/lerna/lerna/issues/397 and https://github.com/lerna/lerna/issues/616. However, this may be the first scenario in which the issue can be easily reproduced.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0-rc.3 |
| `npm --version`  | 4.0.3 |
| `node --version` | 6.9.1 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.12.4 |

**Comment by evocateur** [comment]
@Reinmar Thanks for the repro case!

**Comment by lukebatchelor** [comment]
Interesting, I ran into this issue a while back and was getting very consistent failures. Tried playing with various combinations of yarn, lerna and node to see why this was happening. 

Tried it again today and was seeing the same issue, but cleaned my yarn cache and suddenly everything is working

package|version
----|----
lerna|2.0.0-rc.4
yarn| 0.20.3
node| 7.9.0

```
yarn cache clean
```

**Comment by Reinmar** [comment]
I got a bit different error today, but from what I checked it's also related to concurrency:

https://gist.github.com/Reinmar/b9978b60d09fec1ffc9f55f8d1262349

(this is `npm-debug.log` from one of the packages in which `npm i --global-style` failed)

**Comment by evocateur** [comment]
@Reinmar That error seems to indicate there is invalid JSON in the package.json file? Did the `lerna-debug.log` give any hints?

**Comment by Reinmar** [comment]
Unfortunately, I didn't save it as I went straight to `npm-debug.log` (which is usually more helpful so Lerna could somehow direct the user to it). In the console, as I recall, there was just an info about crashing processes.

I know that the npm log indicates that some JSON was missing/invalid, but I've seen the same error many times in the past. Usually, a second `lerna bootstrap` run would help with that. So, my assumption now, when I discovered that `lerna bootstrap --concurrency=1` helps even more consistently is that:

* one Lerna process starts installing package X,
* a second process tries to install the same package at the same time,
* there's some mutex failure and the second process thinks that the package is already available in npm's cache (`/Users/me/.npm`) but it isn't or is temporarily invalid at that moment,
* the second process crashes while trying to read this file.

And why does it work when running `lerna bootstrap` for the second time (even concurrently)? Because the cache is already hot and all JSONs are usually already unpacked there.

Anyhow reasonable?

**Comment by evocateur** [comment]
That sounds very reasonable. Definitely worthy of further investigation.

**Comment by jwb** [comment]
Do you think it would be fruitful to make an integration test that demonstrates this behavior?

**Comment by evocateur** [comment]
That would definitely be a part of the fix.

**Comment by Reinmar** [comment]
I wonder if [npm 5](http://blog.npmjs.org/post/161081169345/v500) will solve this issue:

> A new, standardised lockfile feature meant for cross-package-manager compatibility (package-lock.json), and a new format and semantics for shrinkwrap. (#16441)

And there's the whole cache rewrite too.

**Comment by DavideDaniel** [comment]
nope. npm5 does not.

**Comment by Brantron** [comment]
We've been able to solve this issue by setting `--mutex network` on the bootstrap command and running our multiple packages in stages. Here's a slimmed down version of our config

```
language: node_js
sudo: required
dist: trusty
node_js:
  - '8'

cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - packages/browser-extension/node_modules
    - packages/frontend/node_modules

before_install:
  - npm i -g yarn@"1.5.1" --cache-min 999999999
  - npm i -g lerna --cache-min 999999999

jobs:
  include:
    - stage: frontend
      script: ./scripts/frontend
      env:
        - SHARD_COUNT=5 SHARD_INDEX=0
    - stage: frontend
      script: ./scripts/frontend
      env:
        - SHARD_COUNT=5 SHARD_INDEX=1
    - stage: frontend
      script: ./scripts/frontend
      env:
        - SHARD_COUNT=5 SHARD_INDEX=2
    - stage: frontend
      script: ./scripts/frontend
      env:
        - SHARD_COUNT=5 SHARD_INDEX=3
    - stage: frontend
      script: ./scripts/frontend
      env:
        - SHARD_COUNT=5 SHARD_INDEX=4
    - stage: extension
      script: ./scripts/extension
```

where scripts frontend is 
```
#!/bin/sh
lerna bootstrap --scope=frontend --mutex network;
(cd packages/frontend && yarn lint);
(cd packages/frontend && yarn test:ci --silent --maxWorkers=4 --coverage)
```
and scripts extension is 
```
#!/bin/sh
lerna bootstrap --scope=browser-extension --mutex network;
(cd packages/browser-extension && yarn lint);
(cd packages/browser-extension && yarn test:ci --silent --maxWorkers=4 --coverage)
```
