### ISSUE TITLE
lerna + travis-ci updated --json shows all packages

### ISSUE THREAD

**Issue by oreporan** [lerna/lerna#918]
## Expected Behavior
I make some code changes, and locally `lerna updated --json` works as expected. But on travis, which starts by cloning. The same line lists all of my packages (though only 1 was changed, without dependencies). 
I would expect this behavior to act the same as on local. All packages depend on one package called common, but I'm not talking about the case when common is changed.

## Current Behavior
I make some code changes, and locally `lerna updated --json` works as expected. But on travis, which starts by cloning. The same line lists all of my packages (though only 1 was changed, without dependencies). 

## Other versions
```
$ node --version
v7.10.1
$ npm --version
4.2.0
$ nvm --version
0.33.2
```
Also - my `yarn install` runs `lerna bootstrap`, is this what I should be doing?
<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.0.0",
  "packages": [
    "packages/*"
  ],
  "version": "independent",
  "npmClient": "yarn"
}
```
</p></details>

<details><summary>travis.yml</summary><p>

```yml
language: node_js
node_js:
  - "7"
branches:
  only:
  - master
before_install:
    - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
install:
  - yarn --pure-lockfile
before_script:
  - git checkout master
  - lerna updated --json
script:
  - lerna run test --since master #This always runs all packages even if only one was changed
  - lerna publish -m "bump versions [ci skip]" --conventional-commits --yes
after_script:
  - git push  
```
</p></details>
